client:
  num_cpus: 8
  num_gpus: 0.2
  type: normal
  epochs: 10
  falloff: 0.0
server:
  num_clients: 5
  fraction_fit: 1.0
  fraction_eval: 1
  min_fit: 5
  min_eval: 5
  num_rounds: 15
  strategy: fedavg
cl:
  num_experiences: 10
  strategy: ewc
  split: random
  ewc_lambda: 0.4
  ewc_decay_factor: null
  ewc_keep_importance_data: false
model:
  name: resnet
  num_classes: 10
  pretrained: false
dataset:
  workload: split_cifar100
  batch_size: 64
  split: iid
  niid:
    alpha: 1.0
    seed: 42
  num_classes: 100
wb:
  project: autofl-testing
  name: f_split_cifar100_ewc_resnet_fedavg_gpu
defaults:
- workload: cifar10
- model: simple_cnn
- _self_
training:
  batch_size: 32
  learning_rate: 0.001
  epochs: 10
  optimizer: adam
