client:
  num_cpus: 8
  num_gpus: 0.25
  type: normal
  epochs: 10
  falloff: 0.0
server:
  num_clients: 4
  fraction_fit: 1.0
  fraction_eval: 1
  min_fit: 4
  min_eval: 4
  num_rounds: 8
  strategy: fedavg
cl:
  num_experiences: 4
  strategy: hybrid
  split: random
  ewc_lambda: 0.4
  replay_mem_size: 300
model:
  name: mobilenet
  num_classes: 10
  version: v3_small
  pretrained: true
dataset:
  workload: cifar10
  batch_size: 128
  split: niid
  niid:
    alpha: 0.5
    seed: 42
  num_classes: 10
wb:
  project: autofl-testing
  name: cifar10_hybrid_mobilenetv3_niid
defaults:
- workload: cifar10
- model: simple_cnn
- _self_
training:
  batch_size: 32
  learning_rate: 0.0005
  epochs: 5
  optimizer: adam
