workload:
  name: cifar10
  domains:
    - original
    - brightness
    - contrast
    - blur
  experiences_per_domain: 2
  transform_params:
    brightness: 0.5
    contrast: 0.5
    blur_kernel: 3 