---
client:
  num_cpus: 2
  num_gpus: 0.25
  type: normal
  epochs: 3
  falloff: 0.0
server:
  num_clients: 5
  fraction_fit: 1
  fraction_eval: 1
  min_fit: 5
  min_eval: 5
  num_rounds: 5
  strategy: fedavg
cl:
  num_experiences: 5
  strategy: naive
  split: class
  ewc:
    lmb: 100
  replay:
    mem_size: 100 
dataset:
  workload: cifar10
  batch_size: 32
  split: iid
  niid:
    alpha: 1.0
    seed: 42
wb:
  project: test-autofl 
  name: testing

