defaults:
  - runtime: sync
  - client: default
  - server: default
  - model: simple_cnn
  - dataset: default
  - async: default
  - latency: default
  - wb: default
  - logging: default
  - optional experiments: null
  - _self_

hydra:
  job:
    chdir: false
  output_subdir: null
  run:
    dir: .
  sweep:
    dir: .
    subdir: multirun/${now:%Y%m%d_%H%M%S}


