# dataset configuration
workload: cifar10  # cifar10, cifar100, bdd100k, kitti, permuted_mnist, split_cifar10
batch_size: 32
num_classes: 10  # auto-detected based on workload

# data distribution options
split: iid  # iid, niid, to still implement and test properly: niid_label, niid_quantity 
niid:
  alpha: 1.0  # dirichlet concentration parameter (lower = more heterogeneous)
  min_samples: 10  # minimum samples per client
  seed: 7
  
  # label-based non-iid options
  classes_per_client: 2  # for niid_label distribution
  
  # quantity-based non-iid options
  quantity_skew: 0.5  # 0.0 = uniform, 1.0 = max skew

# advanced data options
train_test_split: 0.8  # train/validation split ratio
data_seed: 42  # reproducibility
download: true  # auto-download datasets
cache_dir: ./data  # data storage location

# workload-specific options
# mnist:
#   normalize: true
#   flatten: false
  
# cifar:
#   normalize: true
#   augmentation: false  # data augmentation during training
  
# real_world:  # for bdd100k, kitti
#   image_size: [224, 224]
#   crop_center: true 